version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: subscriptions-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ProgramHack
      POSTGRES_DB: subscription
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: subscriptions-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/subscription
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ProgramHack
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db-data: